### ISSUE TITLE
zmienic plan na nowszy

### ISSUE THREAD

**Issue by Teablack** [ptylczynski/wi#10]
na starym planie przesunięto laby z SK i zmiana prowadzących

**Comment by ptylczynski** [comment]
mamy to zrobione? Bo już się zgubiłem z planami xd

**Comment by Teablack** [comment]
nie . To wciąż stary. Na DC jest nowy

**Comment by Teablack** [comment]
zmieniłam, ale moim zdaniem trzeba brać nie DC, bo psuje jakość

**Comment by Teablack** [comment]
co na to powiesz? spoko czy trzeba coś zrobić z jakością?

**Comment by ptylczynski** [comment]
wygląda świetnie, zamknę to w takim razie
